apiVersion: v1
entries:
  gen3:
  - apiVersion: v2
    appVersion: master
    created: "2024-07-25T10:16:17.988643-04:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: file://../ambassador
      version: 0.1.11
    - condition: arborist.enabled
      name: arborist
      repository: file://../arborist
      version: 0.1.11
    - condition: argo-wrapper.enabled
      name: argo-wrapper
      repository: file://../argo-wrapper
      version: 0.1.7
    - condition: audit.enabled
      name: audit
      repository: file://../audit
      version: 0.1.12
    - condition: aws-es-proxy.enabled
      name: aws-es-proxy
      repository: file://../aws-es-proxy
      version: 0.1.9
    - name: common
      repository: file://../common
      version: 0.1.11
    - condition: etl.enabled
      name: etl
      repository: file://../etl
      version: 0.1.1
    - condition: frontend-framework.enabled
      name: frontend-framework
      repository: file://../frontend-framework
      version: 0.1.1
    - condition: fence.enabled
      name: fence
      repository: file://../fence
      version: 0.1.19
    - condition: guppy.enabled
      name: guppy
      repository: file://../guppy
      version: 0.1.12
    - condition: hatchery.enabled
      name: hatchery
      repository: file://../hatchery
      version: 0.1.9
    - condition: indexd.enabled
      name: indexd
      repository: file://../indexd
      version: 0.1.14
    - condition: manifestservice.enabled
      name: manifestservice
      repository: file://../manifestservice
      version: 0.1.14
    - condition: metadata.enabled
      name: metadata
      repository: file://../metadata
      version: 0.1.12
    - condition: peregrine.enabled
      name: peregrine
      repository: file://../peregrine
      version: 0.1.13
    - condition: pidgin.enabled
      name: pidgin
      repository: file://../pidgin
      version: 0.1.10
    - condition: portal.enabled
      name: portal
      repository: file://../portal
      version: 0.1.15
    - condition: requestor.enabled
      name: requestor
      repository: file://../requestor
      version: 0.1.11
    - condition: revproxy.enabled
      name: revproxy
      repository: file://../revproxy
      version: 0.1.16
    - condition: sheepdog.enabled
      name: sheepdog
      repository: file://../sheepdog
      version: 0.1.14
    - condition: ssjdispatcher.enabled
      name: ssjdispatcher
      repository: file://../ssjdispatcher
      version: 0.1.9
    - condition: sower.enabled
      name: sower
      repository: file://../sower
      version: 0.1.11
    - condition: wts.enabled
      name: wts
      repository: file://../wts
      version: 0.1.13
    - condition: global.esdev
      name: elasticsearch
      repository: https://helm.elastic.co
      version: 7.10.2
    - condition: global.dev
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.9.13
    - condition: neuvector.enabled
      name: neuvector
      repository: file://../neuvector
      version: 0.1.0
    description: Helm chart to deploy Gen3 Data Commons
    digest: b7bbdce5e07e0395afda7e908858261805a8a9fc4ba0c9d337e49af271f5cfbc
    maintainers:
    - email: ahilt@uchicago.edu
      name: ahilt
    - email: ajoa@uchicago.edu
      name: ajoaugustine
    - email: emalinowski@uchicago.edu
      name: emalinowski
    - email: elisemcastle@uchicago.edu
      name: EliseCastle23
    - email: qureshi@uchicago.edu
      name: jawadqur
    name: gen3
    type: application
    urls:
    - https://raw.githubusercontent.com/almahmoud/gen3-helm/es/charts/gen3-0.1.99.tgz
    version: 0.1.99
generated: "2024-07-25T10:16:17.954657-04:00"
